import { TopicSection } from '../../src/data/types';

export const distributionsSection: TopicSection = {
  id: "probability-distributions",
  title: "Distributions: The Generated World",
  description: "Understanding how data behaves is the first step in AI. Before we build models, we must understand the 'shape' of our data—the probability distribution that describes how values are clustered or spread across the world.",
  formula: "F_X(x) = P(X \\leq x) = \\int_{-\\infty}^x f(t) \\, dt",
  details: [
    "Random Variables: Assigning numerical values to random outcomes (e.g., rolling a die).",
    "PMF/PDF/CDF: The triplet of mathematical functions that describe every possible distribution.",
    "Data Behavior: Identifying most likely values, rare outliers, and the 'spread' of uncertainty."
  ],
  contentSections: [
    {
      heading: "The Generated World: PMF, PDF, and CDF",
      paragraphs: [
        "In Machine Learning, we assume data is generated by an underlying process. A **Random Variable** is a rule that assigns a numerical value to each outcome. We describe its behavior using three mathematical lenses:  ",
        "1. **PMF (Probability Mass Function)**: For discrete variables, $P(X = x)$. The sum of all probabilities must be 1.  ",
        "2. **PDF (Probability Density Function)**: For continuous variables, $f(x)$. The area under the curve must be 1.  ",
        "3. **CDF (Cumulative Distribution Function)**: The probability that a variable is less than or equal to $x$, $F(x) = P(X \\leq x)$."
      ]
    },
    {
      heading: "Taxonomy of Discrete Distributions",
      paragraphs: [
        "Discrete variables take on specific, countable values. Standard models include:  ",
        "- **Bernoulli**: A single trial with success (p) or failure (q).  ",
        "- **Binomial**: $n$ independent Bernoulli trials. $P(x) = \\binom{n}{x} p^x q^{n-x}$.  ",
        "- **Poisson**: Events occurring in a fixed interval. $P(x) = \\frac{e^{-\\lambda} \\lambda^x}{x!}$.  ",
        "- **Geometric**: Trials until the first success.  ",
        "- **Negative Binomial**: Trials until the $r$-th success.  ",
        "- **Hypergeometric**: Sampling without replacement from a finite population."
      ]
    },
    {
      heading: "Taxonomy of Continuous Distributions",
      paragraphs: [
        "Continuous variables can take any real value in a range. Standard models include:  ",
        "- **Uniform**: All outcomes in $[a, b]$ are equally likely. $f(x) = 1/(b-a)$.  ",
        "- **Normal (Gaussian)**: The 'Bell Curve' centered at $\\mu$. $f(x) = \\frac{1}{\\sigma \\sqrt{2\\pi}} e^{-\\frac{1}{2}(\\frac{x-\\mu}{\\sigma})^2}$.  ",
        "- **Exponential**: Time between events in a Poisson process. $f(x) = \\lambda e^{-\\lambda x}$.  ",
        "- **Gamma**: A generalization of the Exponential and Chi-square distributions.  ",
        "- **Log-Normal**: A variable whose logarithm is normally distributed.  ",
        "- **Chi-Square**: Sum of squares of $k$ independent standard normal variables."
      ],
      code: "import numpy as np\nfrom scipy.stats import norm, binom, poisson, expon\n\n# Binomial: n=10, p=0.5, k=5\nprint(f\"Binomial P(k=5): {binom.pmf(5, 10, 0.5):.4f}\")\n# Poisson: lambda=3, k=2\nprint(f\"Poisson P(k=2): {poisson.pmf(2, 3):.4f}\")\n# Normal PDF at mean (mu=0)\nprint(f\"Normal PDF (z=0): {norm.pdf(0, 0, 1):.4f}\")",
      output: "Binomial P(k=5): 0.2461\nPoisson P(k=2): 0.2240\nNormal PDF (z=0): 0.3989"
    }
  ],
  tags: ["PMF", "PDF", "Gaussian", "Poisson", "Bernoulli", "MLE"],
  level: "Intermediate"
};
